name = "isa2026-api"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-07-24"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "2026isadb"
database_id = "3fc30442-2485-4d75-98d5-32d20c5dc5a8"

[[kv_namespaces]]
binding = "KV"
id = "c187ffbf9da446e9bd939b960c4fc68b"

[observability]
enabled = true
head_sampling_rate = 1
